(function(x,y,z,A,B,k,C,n,p,q,D,E,r,F,G,H,s,I,K,t,u,L,v,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,$,aa,ba,ca,da,ea,fa,ga,ha,ia,ja,ka,la,ma,na,oa,pa,qa,ra,e,f){Jmol.Console={buttons:{},buttonWidth:100,click:function(a){Jmol.Console.buttons[a].console.appletConsole.doAction(Jmol.Console.buttons[a])}};Jmol.Console.Image=function(a,c,b){this.vwr=a;this.title=c;this.imageMap=b;this.applet=a.html5Applet;a=this.applet._id+"_Image";this.id=a+"_"+(""==c?"app":c).replace(/\W/g,"_");var d=Jmol._$(this.id+"_holder");if(!d[0]&&
(d=Jmol._$(a+"_holder"))[0])this.id=a;d[0]?this.div=d:Jmol.Console.createDOM(this,'<div id="$ID" class="jmolImage" style="display:block;background-color:yellow;position:absolute;z-index:'+ ++Jmol._z.consoleImage+'"><div id="$ID_title"></div><div id="$ID_holder"></div></div>');System.out.println("image "+this.id+" created");(a=b.get(this.id))&&a.closeMe();b.put(this.id,this);b.put(c,this)};Jmol.Console.Image.setCanvas=function(a,c){Jmol.$append(Jmol._$(a.id+"_holder"),c);Jmol.$html(a.id+"_title","<table style='width:100%'><tr><td>&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"javascript:Jmol.Console.buttons['"+
a.id+"'].closeMe()\">close</a></td><td align=right>"+a.title+" ["+c.width+" x "+c.height+"]</td></tr></table>")};Jmol.Console.Image.closeImage=function(a){a.imageMap.remove(a.title);a.imageMap.remove(a.id);a.div?Jmol.$remove(a.cid):(a.dragBind(!1),Jmol.$remove(a.id))};Jmol.Console.Image.prototype.setImage=function(a){this.cid&&Jmol.$remove(this.cid);var c=document.createElement("canvas");c.width=a.width;c.height=a.height;var b=c.getContext("2d");if(a.buf32){var d=b.getImageData(0,0,c.width,c.height),
h=d.data;a=a.buf32;for(var w=h.length>>2,e=0,g=0;e<w;e++)h[g++]=a[e]>>16&255,h[g++]=a[e]>>8&255,h[g++]=a[e]&255,h[g++]=255;b.putImageData(d,0,0)}else b.drawImage(a,0,0);this.cid=c.id=this.id+"_image";Jmol.Console.Image.setCanvas(this,c)};Jmol.Console.Image.prototype.closeMe=function(){Jmol.Console.Image.closeImage(this)};Jmol.Swing.setDraggable(Jmol.Console.Image);Jmol.Console.createDOM=function(a,c){var b=a.id;Jmol.Console.buttons[b]=a;c=c.replace(/\$ID/g,b);Jmol.$after("body",c);a.setContainer(Jmol._$(b));
a.setPosition();a.dragBind(!0)};Jmol.Console.JSConsole=function(a){this.applet=a.vwr.html5Applet;var c=this.id=this.applet._id+"_console",b=this;b.appletConsole=a;b.input=a.input=new Jmol.Console.Input(b);b.output=a.output=new Jmol.Console.Output(b);var d='<div id="$ID" class="jmolConsole" style="display:block;background-color:yellow;width:600px;height:362px;position:absolute;z-index:'+Jmol._z.console+'"><div id=$ID_title></div><div id=$ID_label1></div><div id=$ID_outputdiv style="position:relative;left:2px"></div><div id=$ID_inputdiv style="position:relative;left:2px"></div><div id=$ID_buttondiv></div></div>';
Jmol.Console.createDOM(this,d);d="&nbsp;&nbsp;&nbsp;&nbsp;<a href=\"javascript:Jmol.Console.buttons['"+c+"'].setVisible(false)\">close</a>"+('&nbsp;&nbsp;&nbsp;&nbsp;<a href="javascript:Jmol.script('+b.applet._id+",'help')\">help</a>");Jmol.$html(c+"_label1",d);Jmol.$html(c+"_inputdiv",'<textarea id="'+c+'_input" style="width:590px;height:100px"></textarea>');Jmol.$html(c+"_outputdiv",'<textarea id="'+c+'_output" style="width:590px;height:200px"></textarea>');d=function(a,b){b.console=a;b.id=c+"_"+
b.label.replace(/\s/g,"_");Jmol.Console.buttons[b.id]=b;return b.html()};d=d(b,a.runButton)+d(b,a.loadButton)+d(b,a.clearInButton)+d(b,a.clearOutButton)+d(b,a.historyButton)+d(b,a.stateButton);Jmol.$html(c+"_buttondiv",d);Jmol.$bind("#"+c+"_input","keydown keypress keyup",function(a){b.input.keyEvent(a)});Jmol.$bind("#"+c+"_input","mousedown touchstart",function(){b.ignoreMouse=!0});Jmol.$bind("#"+c+"_output","mousedown touchstart",function(){b.ignoreMouse=!0});b.setButton=function(a){return new Jmol.Console.Button(this,
a)};b.setVisible=function(a){a?this.container.show():this.container.hide();this.dragBind(a)};b.setTitle=function(){};b.setVisible(!1)};Jmol.Swing.setDraggable(Jmol.Console.JSConsole);Jmol.Console.Input=function(a){this.console=a;this.id=a.id+"_input";this.getText=function(){return Jmol.$val(this.id)};this.setText=function(a){null==a&&(a="");Jmol.$val(this.id,a)};this.keyEvent=function(a){var b;b=a.type;var d=a.ctrlKey,h=a.keyCode;13==h&&(h=10);if("keyup"==b)b=38==h||40==h?1:this.console.appletConsole.processKey(h,
402,d),1==(b&1)&&a.preventDefault();else{var e="keydown"==b,f=e?a.key||a.originalEvent.keyIdentifier:"";switch(h){case 38:case 40:e||(h=0);break;case 8:case 9:case 10:case 27:break;default:h=0}b=this.console.appletConsole.processKey(h,401,d);d&&10==h&&this.setText(this.getText()+"\n");if(0==b&&9==a.keyCode){var g=this;setTimeout(function(){g.setText(g.getText()+"\t");Jmol.$focus(g.id)},10)}(1==(b&1)||"Up"==f||"Down"==f||e&&8!=a.keyCode&&32>a.keyCode)&&a.preventDefault()}};this.getCaretPosition=function(){var a=
Jmol._$(this.id)[0];if("selectionStart"in a)return a.selectionStart;if(!("selection"in document))return 0;a.focus();var b=document.selection.createRange(),d=document.selection.createRange().text.length;b.moveStart("character",-a.value.length);return b.text.length-d}};Jmol.Console.Output=function(a){this.id=a.id+"_output";this.getText=function(){return Jmol.$val(this.id)};this.setText=function(a){null==a&&(a="");Jmol.$val(this.id,a)};this.append=function(a){this.setText(this.getText()+a);Jmol.$scrollTo(this.id,
-1)}};Jmol.Console.Button=function(a){this.label=a};Jmol.Console.Button.prototype.addConsoleListener=function(a){this.appletConsole=a;Jmol.Console.buttons[this.id]=this};Jmol.Console.Button.prototype.html=function(){return'<input type="button" id="'+this.id+'" style="width:'+Jmol.Console.buttonWidth+'px" value="'+this.label+'" onClick="Jmol.Console.click(\''+this.id+"')\"/>"};k("J.console");v(J.console,"GenericTextArea");k("J.console");n(["J.api.JmolAppConsoleInterface","$.JmolCallbackListener","java.util.Hashtable"],
"J.console.GenericConsole","java.lang.Boolean JU.PT J.c.CBK J.i18n.GT JS.T JV.Viewer".split(" "),function(){c$=q(function(){this.label1=this.defaultMessage=this.loadButton=this.clearInButton=this.clearOutButton=this.stateButton=this.historyButton=this.runButton=this.editButton=this.menuMap=this.vwr=this.output=this.input=null;this.nTab=0;this.incompleteCmd=null;p(this,arguments)},J.console,"GenericConsole",null,[J.api.JmolAppConsoleInterface,J.api.JmolCallbackListener]);t(c$,function(){this.menuMap=
new java.util.Hashtable});e(c$,"setViewer",function(a){this.vwr=a;null==J.console.GenericConsole.labels&&(a=new java.util.Hashtable,a.put("title",J.i18n.GT._("Jmol Script Console")+" "+JV.Viewer.getJmolVersion()),this.setupLabels(a),J.console.GenericConsole.labels=a)},"JV.Viewer");e(c$,"addButton",function(a,c){a.addConsoleListener(this);this.menuMap.put(c,a);return a},"J.api.JmolAbstractButton,~S");e(c$,"getLabel1",function(){return null});e(c$,"setupLabels",function(a){a.put("saveas",J.i18n.GT._("&Save As..."));
a.put("file",J.i18n.GT._("&File"));a.put("close",J.i18n.GT._("&Close"));this.setupLabels0(a)},"java.util.Map");e(c$,"setupLabels0",function(a){a.put("help",J.i18n.GT._("&Help"));a.put("search",J.i18n.GT._("&Search..."));a.put("commands",J.i18n.GT._("&Commands"));a.put("functions",J.i18n.GT._("Math &Functions"));a.put("parameters",J.i18n.GT._("Set &Parameters"));a.put("more",J.i18n.GT._("&More"));a.put("Editor",J.i18n.GT._("Editor"));a.put("State",J.i18n.GT._("State"));a.put("Run",J.i18n.GT._("Run"));
a.put("Clear Output",J.i18n.GT._("Clear Output"));a.put("Clear Input",J.i18n.GT._("Clear Input"));a.put("History",J.i18n.GT._("History"));a.put("Load",J.i18n.GT._("Load"));a.put("label1",J.i18n.GT._("press CTRL-ENTER for new line or paste model data and press Load"));a.put("default",J.i18n.GT._("Messages will appear here. Enter commands in the box below. Click the console Help menu item for on-line help, which will appear in a new browser window."))},"java.util.Map");e(c$,"setLabels",function(){var a=
J.i18n.GT.setDoTranslate(!0);this.editButton=this.setButton("Editor");this.stateButton=this.setButton("State");this.runButton=this.setButton("Run");this.clearOutButton=this.setButton("Clear Output");this.clearInButton=this.setButton("Clear Input");this.historyButton=this.setButton("History");this.loadButton=this.setButton("Load");this.defaultMessage=J.console.GenericConsole.getLabel("default");this.setTitle();J.i18n.GT.setDoTranslate(a)});c$.getLabel=e(c$,"getLabel",function(a){return J.console.GenericConsole.labels.get(a)},
"~S");e(c$,"displayConsole",function(){this.layoutWindow(null);this.outputMsg(this.defaultMessage)});e(c$,"updateLabels",function(){});e(c$,"completeCommand",function(a){if(0==a.length)return null;var c=0>=this.nTab||null==this.incompleteCmd?a:this.incompleteCmd;this.incompleteCmd=c;a=J.console.GenericConsole.splitCommandLine(a);if(null==a)return null;var b=null==a[2],d=null!=a[3],h=a[b?1:2],e=a[1];if(0==h.length)return null;a=JS.T.getTokenFromName(e.trim().toLowerCase());var f=JS.T.tokAttr(null==
a?0:a.tok,12288);a=J.console.GenericConsole.splitCommandLine(c);var g=null;if(!b&&('"'==h.charAt(0)||"'"==h.charAt(0)))b=h.charAt(0),JU.PT.trim(h,"\"'"),h=JU.PT.trim(a[2],"\"'"),g=this.nextFileName(h,this.nTab),null!=g&&(g=a[0]+a[1]+b+g+b);else{g=null;if(!b&&(h=e,d||a[2].startsWith("$")||f))g=new java.util.Hashtable,this.vwr.getObjectMap(g,d||f?"{":a[2].startsWith("$")?"$":"0");g=JS.T.completeCommand(g,e.equalsIgnoreCase("set "),b,b?a[1]:a[2],this.nTab);g=a[0]+(null==g?h:b?g:a[1]+g)}return null==
g||g.equals(c)?null:g},"~S");e(c$,"doAction",function(a){if(a===this.runButton)this.execute(null);else if(a===this.editButton)this.vwr.getProperty("DATA_API","scriptEditor",null);else if(a===this.historyButton)this.clearContent(this.vwr.getSetHistory(2147483647));else if(a===this.stateButton)this.clearContent(this.vwr.getStateInfo());else if(a===this.clearInButton){this.input.setText("");return}a===this.clearOutButton?this.output.setText(""):a===this.loadButton?this.vwr.loadInlineAppend(this.input.getText(),
!1):this.isMenuItem(a)&&this.execute(a.getName())},"~O");e(c$,"execute",function(a){var c=null==a?this.input.getText():a;null==a&&this.input.setText(null);a=this.vwr.script(c+"\u0001## EDITOR_IGNORE ##");null!=a&&!a.equals("pending")&&this.outputMsg(a)},"~S");e(c$,"destroyConsole",function(){this.vwr.isApplet&&this.vwr.getProperty("DATA_API","getAppConsole",Boolean.FALSE)});c$.setAbstractButtonLabels=e(c$,"setAbstractButtonLabels",function(a,c){for(var b,d=a.keySet().iterator();d.hasNext()&&((b=d.next())||
1);){var h=a.get(b),e=c.get(b);if(b.indexOf("Tip")==b.length-3)h.setToolTipText(c.get(b));else{var f=J.console.GenericConsole.getMnemonic(e);" "!=f&&h.setMnemonic(f);e=J.console.GenericConsole.getLabelWithoutMnemonic(e);h.setText(e)}}},"java.util.Map,java.util.Map");c$.getLabelWithoutMnemonic=e(c$,"getLabelWithoutMnemonic",function(a){if(null==a)return null;var c=a.indexOf("&");return-1==c?a:a.substring(0,c)+(c<a.length-1?a.substring(c+1):"")},"~S");c$.getMnemonic=e(c$,"getMnemonic",function(a){if(null==
a)return" ";var c=a.indexOf("&");return-1==c||c==a.length-1?" ":a.charAt(c+1)},"~S");c$.map=e(c$,"map",function(a,c,b,d){b=J.console.GenericConsole.getMnemonic(b);" "!=b&&a.setMnemonic(b);null!=d&&d.put(c,a)},"~O,~S,~S,java.util.Map");f(c$,"notifyEnabled",function(a){switch(a){case J.c.CBK.ECHO:case J.c.CBK.MEASURE:case J.c.CBK.MESSAGE:case J.c.CBK.PICK:return!0}return!1},"J.c.CBK");f(c$,"notifyCallback",function(a,c){var b=null==c||null==c[1]?null:c[1].toString();switch(a){case J.c.CBK.ECHO:this.sendConsoleEcho(b);
break;case J.c.CBK.MEASURE:var d=c[3];0<=d.indexOf("Picked")||0<=d.indexOf("Sequence")?this.sendConsoleMessage(b):0<=d.indexOf("Completed")&&this.sendConsoleEcho(b.substring(b.lastIndexOf(",")+2,b.length-1));break;case J.c.CBK.MESSAGE:this.sendConsoleMessage(null==c?null:b);break;case J.c.CBK.PICK:this.sendConsoleMessage(b)}},"J.c.CBK,~A");f(c$,"getText",function(){return this.output.getText()});f(c$,"sendConsoleEcho",function(a){null==a?(this.updateLabels(),this.outputMsg(null),a=this.defaultMessage):
a.equals("\x00")&&(Clazz_Console.clear(),a=null);this.outputMsg(a)},"~S");e(c$,"outputMsg",function(a){null==a?this.output.setText(""):("\n"!=a.charAt(a.length-1)&&(a+="\n"),this.output.append(a))},"~S");e(c$,"clearContent",function(a){this.output.setText(a)},"~S");f(c$,"sendConsoleMessage",function(a){null!=a&&this.output.getText().startsWith(this.defaultMessage)&&this.outputMsg(null);this.outputMsg(a)},"~S");f(c$,"setCallbackFunction",function(){},"~S,~S");f(c$,"zap",function(){});e(c$,"recallCommand",
function(a){a=this.vwr.getSetHistory(a?-1:1);null!=a&&this.input.setText(JU.PT.escUnicode(a))},"~B");e(c$,"processKey",function(a,c,b){var d=0;switch(c){case 401:switch(a){case 9:c=this.input.getText();if(c.endsWith("\n")||c.endsWith("\t"))return 0;d=1;if(this.input.getCaretPosition()==c.length)return a=this.completeCommand(c),null!=a&&this.input.setText(JU.PT.escUnicode(a).$replace("\t"," ")),this.nTab++,d;break;case 27:d=1,this.input.setText("")}this.nTab=0;if(10==a&&!b)return this.execute(null),
d;if(38==a||40==a)return this.recallCommand(38==a),d;break;case 402:if(10==a&&!b)return d}return d|2},"~N,~N,~B");c$.splitCommandLine=e(c$,"splitCommandLine",function(a){var c=Array(4),b=!1,d=!1,e=!1;if(0==a.length)return null;for(var f=-1,l=0,g=0,m=0,k,j=0;j<a.length;j++){switch(k=a.charAt(j)){case '"':!e&&!b&&(d=!d)&&(f=g=j);break;case "'":!e&&!d&&(b=!b)&&(f=g=j);break;case "\\":e=!e;continue;case " ":!e&&(!b&&!d)&&(g=j+1,f=-1);break;case ";":!b&&!d&&(l=g=j+1,f=-1,m=0);break;case "{":case "}":!b&&
!d&&(m+="{"==k?1:-1,g=j+1,f=-1);break;default:!b&&!d&&(f=-1)}e=!1}c[0]=a.substring(0,l);c[1]=g==l?a.substring(l):a.substring(l,g>f?g:f);c[2]=g==l?null:a.substring(g);c[3]=0<m?"{":null;return c},"~S");s(c$,"labels",null)});k("J.consolejs");n(["J.console.GenericConsole"],"J.consolejs.AppletConsole",null,function(){c$=q(function(){this.jsConsole=null;p(this,arguments)},J.consolejs,"AppletConsole",J.console.GenericConsole);r(c$,function(){u(this,J.consolejs.AppletConsole,[])});f(c$,"start",function(a){this.setViewer(a);
this.setLabels();this.displayConsole()},"JV.Viewer");f(c$,"layoutWindow",function(){this.jsConsole=new Jmol.Console.JSConsole(this);this.setTitle()},"~S");f(c$,"setTitle",function(){this.jsConsole&&this.jsConsole.setTitle(this.getLabel("title"))});f(c$,"setVisible",function(a){this.jsConsole.setVisible(a)},"~B");f(c$,"setButton",function(a){return new Jmol.Console.Button(a)},"~S");f(c$,"dispose",function(){this.setVisible(!1)});f(c$,"isMenuItem",function(){return!1},"~O");f(c$,"getScriptEditor",function(){return null});
f(c$,"nextFileName",function(){return null},"~S,~N");f(c$,"newJMenu",function(){return null},"~S");f(c$,"newJMenuItem",function(){return null},"~S")})})(Clazz,Clazz.newLongArray,Clazz.doubleToByte,Clazz.doubleToInt,Clazz.doubleToLong,Clazz.declarePackage,Clazz.instanceOf,Clazz.load,Clazz.instantialize,Clazz.decorateAsClass,Clazz.floatToInt,Clazz.floatToLong,Clazz.makeConstructor,Clazz.defineEnumConstant,Clazz.exceptionOf,Clazz.newIntArray,Clazz.defineStatics,Clazz.newFloatArray,Clazz.declareType,
Clazz.prepareFields,Clazz.superConstructor,Clazz.newByteArray,Clazz.declareInterface,Clazz.p0p,Clazz.pu$h,Clazz.newShortArray,Clazz.innerTypeInstance,Clazz.isClassDefined,Clazz.prepareCallback,Clazz.newArray,Clazz.castNullAs,Clazz.floatToShort,Clazz.superCall,Clazz.decorateAsType,Clazz.newBooleanArray,Clazz.newCharArray,Clazz.implementOf,Clazz.newDoubleArray,Clazz.overrideConstructor,Clazz.clone,Clazz.doubleToShort,Clazz.getInheritedLevel,Clazz.getParamsType,Clazz.isAF,Clazz.isAI,Clazz.isAS,Clazz.isASS,
Clazz.isAP,Clazz.isAFloat,Clazz.isAII,Clazz.isAFF,Clazz.isAFFF,Clazz.tryToSearchAndExecute,Clazz.getStackTrace,Clazz.inheritArgs,Clazz.alert,Clazz.defineMethod,Clazz.overrideMethod,Clazz.declareAnonymous,Clazz.cloneFinals);
